version: v1
managed:
  enabled: true
  go_package_prefix:
    default: "github.com/expect-digital/translate/pkg/server/translate/v1"
    except:
      - buf.build/googleapis/googleapis
plugins:
  - remote: buf.build/grpc-ecosystem/plugins/openapiv2
    out: gen/openapiv2
